### ISSUE TITLE
Github button is getting stretched 

### ISSUE THREAD

**Issue by RingoKam** [nycJSorg/angular-presentation#513] opened 2017-06-17 00:03 UTC
Oh Noz What happen to you Octocat!?

![image](https://user-images.githubusercontent.com/10913199/27248229-ab183192-52ce-11e7-87cc-0c571189b61c.png)

Github button is distorted on the index page.

**Comment by tessaSAC** [comment] 2017-06-17 06:59
Lolol. Someone else showed this to me last week as well. I only got this once by having dev tools open when loading then closing them. Was not able to reproduce for a screencap.

**Comment by RingoKam** [comment] 2017-06-17 13:27
should have just debugged it last night. 

![image](https://user-images.githubusercontent.com/10913199/27253101-d2823ada-533b-11e7-80bd-13ae56db5f68.png)

seems the issue is caused by 
![image](https://user-images.githubusercontent.com/10913199/27253253-140a2e42-533f-11e7-8522-60f7fbc02a1e.png)

Give the angular logo a specific class should fix the issue (rather than all img)?

**Comment by burrack** [comment] 2017-06-30 23:10
someone fixed it
I'm closing

**Closed** 2017-06-30 23:11 UTC
