### ISSUE TITLE
Explain @ symbol and Angular exports

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#361] opened 2017-05-13 20:57 UTC
Use of @ symbol should be explained further.

Also, how we're magically able to export 'Hello World Component'. Is Angular doing this for us behind the scenes when we use the Component syntax shown above?
Author: Saif Tase
Slide: [Local](http://localhost:4200/create-first-app/component),[Public](https://angular-presentation.firebaseapp.com/create-first-app/component)

**Comment by kirjs** [comment] 2017-05-13 21:20
More feedback from the same slide, not necessarily in the right order.


I guess this is sort of answered in the following slides, but if the student is trying to understand each slide fully before moving on, they might not realize this.

Joseph Barlan (Step 1: Create component)
I agree with Saif. I think it would be be better to explain that we are creating a class first, then we're decorating it with @Component() in the next slide so that looking at this slide doesn't feel like something is missing.

Joseph Barlan (Step 1: Create component)
Looking at the exercise a few slides down, it makes sense I think to introduce classes first before decorating it as that is also the workflow given in the exercise.

Joseph Barlan (Step 1: Create component)
without the decorator i mean
Take  Close [Duplicate]  Close [No fix] Close [Done]  Close [Nice message] Close [Can't reproduce]

**Comment by tessaSAC** [comment] 2017-05-18 04:59
Joseph's comments mostly a duplicate of #407 dedicated to his comments

**Comment by tessaSAC** [comment] 2017-05-18 05:02
Maybe Saif's second comment could be addressed by #274?

**Comment by tessaSAC** [comment] 2017-06-11 08:03
Moving to #494

**Closed by tessaSAC** 2017-06-11 08:03 UTC
